#=========================================================================
# run_test.yml
#=========================================================================

name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sim:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install verilator
        run: |
          wget --progress=dot:giga https://github.com/pymtl/verilator-ci-cache/raw/master/verilator-github-actions-5.026.tar.gz
          echo $PWD
          whoami
          tar -C ${HOME} -xzf verilator-github-actions-5.026.tar.gz
          echo "${HOME}/verilator/bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=${HOME}/verilator/share/pkgconfig:${PKG_CONFIG_PATH}" >> $GITHUB_ENV

      - name: Check verilator
        run: |
          which verilator
          verilator --version
          pkg-config --modversion verilator
          pkg-config --cflags verilator

      - name: Install dependencies
        run: |
          sudo apt-get install -y iverilog

      - name: Run sim tests
        timeout-minutes: 10
        run: |
          verilator -Wall --lint-only PairTripleDetector.v
          iverilog -Wall -g2012 -o PairTripleDetector_test \
            PairTripleDetector_test.v \
            PairTripleDetector.v
          ./PairTripleDetector_test +verbose=-1 | tee PairTripleDetector_test.log
          grep "*** PASSED ***" PairTripleDetector_test.log
